language: haskell
before_install:
  wget --quiet -O ghc.tar.bz2 http://www.haskell.org/ghc/dist/7.6.1/ghc-7.6.1-i386-unknown-linux.tar.bz2
  tar xf ghc.tar.bz2
  cd ghc-7.6.1/
  sudo apt-get install libgmp3c2 libgmp3-dev  zlib libghc-zlib-dev
  ./configure
  make
  make install
  cabal install cabal-install
  cabal update
  ghc --version
  cabal --version

